# Generated by Django 6.0.3 on 2026-04-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_time_per_task',
            field=models.FloatField(default=0.0, help_text='Avg time taken per task in hours'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deadlines_met',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('professional', 'Professional'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_strength',
            field=models.CharField(blank=True, help_text='Most frequent task type', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
