# Generated by Django 6.0.3 on 2026-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0003_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='github_repo',
            field=models.CharField(blank=True, help_text='Format: owner/repo-name', max_length=200),
        ),
    ]
