# Generated by Django 6.0.3 on 2026-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0004_workspace_github_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
