# Generated by Django 6.0.3 on 2026-05-23 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0005_channel_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_project_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='qualified_employees',
            field=models.ManyToManyField(blank=True, related_name='qualified_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChannelMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='slack_app.channel')),
            ],
        ),
    ]
